import { ActivityMasterType, ActivityLog, BuyerLead, PropertyItem, CustomerLead, TagItem } from './types';

export const initialActivityMasters: ActivityMasterType[] = [
  // Current Activites (Daily Pipeline & Days Elapsed Tracker)
  {
    id: 'act-1',
    name: 'Update on Job',
    code: 'ACT_UPDATE_JOB',
    category: 'Other',
    activityGroup: 'current',
    description: 'Status update on current job, lead progression, assignments, and workflow follow-up',
    iconName: 'RefreshCw',
    color: '#0284c7',
    defaultDurationMinutes: 15,
    isSystem: true,
  },
  {
    id: 'act-2',
    name: 'Staff - Mobile Call',
    code: 'ACT_STAFF_CALL',
    category: 'Call',
    activityGroup: 'current',
    description: 'Direct mobile cellular telephone call by executive staff with lead, client, or mediator',
    iconName: 'Phone',
    color: '#3b82f6',
    defaultDurationMinutes: 10,
    isSystem: true,
  },
  {
    id: 'act-3',
    name: 'Staff - 121',
    code: 'ACT_STAFF_121',
    category: 'Meeting',
    activityGroup: 'current',
    description: 'Staff one-to-one in-person consultation in company office or client location',
    iconName: 'Users',
    color: '#8b5cf6',
    defaultDurationMinutes: 30,
    isSystem: true,
  },
  {
    id: 'act-4',
    name: 'MD - Mobile Call',
    code: 'ACT_MD_CALL',
    category: 'Call',
    activityGroup: 'current',
    description: 'Managing Director direct high-level telephonic discussion and strategic guidance',
    iconName: 'PhoneCall',
    color: '#f59e0b',
    defaultDurationMinutes: 15,
    isSystem: true,
  },
  {
    id: 'act-5',
    name: 'MD - 121',
    code: 'ACT_MD_121',
    category: 'Meeting',
    activityGroup: 'current',
    description: 'Managing Director direct in-person executive conference, closing, or review',
    iconName: 'Building2',
    color: '#ef4444',
    defaultDurationMinutes: 45,
    isSystem: true,
  },

  // Pending Activites (Field Milestones & Verification Actions)
  {
    id: 'act-6',
    name: 'Property Document Collection',
    code: 'ACT_DOC_COLL',
    category: 'Visit',
    activityGroup: 'pending',
    description: 'Field visit to collect parent documents, patta, chitta, encumbrance certificate (EC), and title deeds',
    iconName: 'FileText',
    color: '#10b981',
    defaultDurationMinutes: 60,
    isSystem: true,
  },
  {
    id: 'act-7',
    name: 'Property R/D',
    code: 'ACT_PROP_RD',
    category: 'Visit',
    activityGroup: 'pending',
    description: 'On-site research and development, physical boundary inspection, guideline value and market assessment',
    iconName: 'MapPin',
    color: '#06b6d4',
    defaultDurationMinutes: 60,
    isSystem: true,
  },
  {
    id: 'act-8',
    name: 'Property Photo and Video',
    code: 'ACT_PHOTO_VIDEO',
    category: 'Visit',
    activityGroup: 'pending',
    description: 'Capturing high-resolution photographs, 4K walkthrough video, drone footage, and visual marketing assets',
    iconName: 'Camera',
    color: '#6366f1',
    defaultDurationMinutes: 60,
    isSystem: true,
  },
  {
    id: 'act-9',
    name: 'Buyer and Seller meeting',
    code: 'ACT_BUYER_SELLER_MEET',
    category: 'Meeting',
    activityGroup: 'pending',
    description: 'Joint direct face-to-face deal negotiation between Buyer and Seller with management supervision',
    iconName: 'Handshake',
    color: '#ec4899',
    defaultDurationMinutes: 60,
    isSystem: true,
  },

  // Supplementary Standard Activities
  {
    id: 'act-10',
    name: 'Property visit',
    code: 'VISIT_PROP',
    category: 'Visit',
    activityGroup: 'current',
    description: 'On-site physical inspection and land/flat walkthrough with potential buyer',
    iconName: 'Home',
    color: '#14b8a6',
    defaultDurationMinutes: 60,
    isSystem: true,
  },
  {
    id: 'act-11',
    name: 'Buyer and Customer Mobile Conference',
    code: 'CONF_MOB',
    category: 'Conference',
    activityGroup: 'current',
    description: 'Telephonic 3-way conference between buyer, property seller/customer, and mediator',
    iconName: 'PhoneCall',
    color: '#eab308',
    defaultDurationMinutes: 20,
    isSystem: true,
  },
];

export const initialTags: TagItem[] = [
  // Enquiry Source
  { id: 'tag-es-1', category: 'enquiry_source', name: 'Property Plus', color: '#2563eb' },
  { id: 'tag-es-2', category: 'enquiry_source', name: 'Facebook', color: '#1877f2' },
  { id: 'tag-es-3', category: 'enquiry_source', name: 'Nanganallur Voice', color: '#059669' },
  { id: 'tag-es-4', category: 'enquiry_source', name: 'Nanganallur Speaks', color: '#0d9488' },
  { id: 'tag-es-5', category: 'enquiry_source', name: 'Times of India', color: '#dc2626' },
  { id: 'tag-es-6', category: 'enquiry_source', name: 'On-site Board', color: '#d97706' },
  { id: 'tag-es-7', category: 'enquiry_source', name: 'Walk-in', color: '#7c3aed' },
  { id: 'tag-es-8', category: 'enquiry_source', name: 'Referral / Mediator', color: '#4b5563' },

  // Buyer Status
  { id: 'tag-bs-1', category: 'buyer_status', name: 'New Lead', color: '#3b82f6' },
  { id: 'tag-bs-2', category: 'buyer_status', name: 'Potential Buyer', color: '#8b5cf6' },
  { id: 'tag-bs-3', category: 'buyer_status', name: 'Site Visit Scheduled', color: '#f59e0b' },
  { id: 'tag-bs-4', category: 'buyer_status', name: 'In Negotiation', color: '#d97706' },
  { id: 'tag-bs-5', category: 'buyer_status', name: 'Approved & Locked', color: '#10b981' },
  { id: 'tag-bs-6', category: 'buyer_status', name: 'Deal Closed', color: '#059669' },
  { id: 'tag-bs-7', category: 'buyer_status', name: 'Not Interested / Dropped', color: '#6b7280' },

  // Customer Status
  { id: 'tag-cs-1', category: 'customer_status', name: 'New Lead', color: '#3b82f6' },
  { id: 'tag-cs-2', category: 'customer_status', name: 'Potential Customer', color: '#8b5cf6' },
  { id: 'tag-cs-3', category: 'customer_status', name: 'Inspection Pending', color: '#f59e0b' },
  { id: 'tag-cs-4', category: 'customer_status', name: 'Approved & Locked', color: '#10b981' },
  { id: 'tag-cs-5', category: 'customer_status', name: 'Exclusive Mandate', color: '#06b6d4' },
  { id: 'tag-cs-6', category: 'customer_status', name: 'Archived', color: '#6b7280' },
];

export const initialProperties: PropertyItem[] = [
  {
    id: 'prop-1',
    date: '2026-08-15',
    title: '20th Street Residential Plot',
    propertyCode: 'PROP-20ST-01',
    propertyType: 'Plot',
    locality: 'Nanganallur',
    address: 'Plot No 14, 20th Street, Nanganallur, Chennai',
    sizeSqFt: 2400,
    groundArea: '1 Ground (40 x 60)',
    facing: 'North-East',
    roadWidthFt: 24,
    price: '2.50 Cr',
    priceNumeric: 25000000,
    ownerName: 'Venkatesan MD Trust',
    ownerContact: '+91 94440 26113',
    availableFrom: '2025-11-30',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&auto=format&fit=crop&q=60',
    isPotential: true,
    isApproved: true,
    isLocked: true,
    lockedAt: '2026-08-15',
    lockedBy: 'Admin',
    crmStage: 'Active Marketing',
    features: ['Corner Plot', 'Clear Patta Land', '24ft Road', 'Metro Connectivity'],
    onlineAdsPostedCount: 31,
    totalSiteVisits: 14,
  },
  {
    id: 'prop-2',
    date: '2026-08-10',
    title: 'Guduvanchery Township Plots',
    propertyCode: 'PROP-GDV-02',
    propertyType: 'Plot',
    locality: 'Guduvanchery',
    address: 'Survey No 128, Near Railway Station, Guduvanchery',
    sizeSqFt: 1800,
    groundArea: '1800 Sqft',
    facing: 'East',
    roadWidthFt: 30,
    price: '48 Lakhs',
    priceNumeric: 4800000,
    ownerName: 'Guduvanchery Promoters',
    ownerContact: '+91 96295 93818',
    availableFrom: '2026-06-04',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1524813686514-a57563d77d66?w=600&auto=format&fit=crop&q=60',
    isPotential: true,
    isApproved: true,
    isLocked: true,
    lockedAt: '2026-08-10',
    lockedBy: 'Admin',
    crmStage: 'Active Marketing',
    features: ['DTCP Approved', 'Gated Community', 'Blacktop Roads', 'Street Lights'],
    onlineAdsPostedCount: 31,
    totalSiteVisits: 8,
  },
  {
    id: 'prop-3',
    date: '2026-09-02',
    title: 'Urapakkam Villa Plots',
    propertyCode: 'PROP-URP-03',
    propertyType: 'Plot',
    locality: 'Urapakkam',
    address: 'Sector 4, Urapakkam West, GST Road access',
    sizeSqFt: 1500,
    groundArea: '1500 Sqft',
    facing: 'North',
    roadWidthFt: 30,
    price: '42 Lakhs',
    priceNumeric: 4200000,
    ownerName: 'Urapakkam Housing Board',
    ownerContact: '+91 98409 10807',
    availableFrom: '2025-11-01',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&auto=format&fit=crop&q=60',
    isPotential: true,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-02',
    isApproved: false,
    isLocked: false,
    crmStage: 'Admin Approval',
    features: ['Near Kilambakkam Bus Terminus', 'Ready to Build', 'Sweet Water'],
    onlineAdsPostedCount: 31,
    totalSiteVisits: 6,
  },
  {
    id: 'prop-4',
    title: 'Karthikeyapuram Premium 2 BHK Flat',
    propertyCode: 'PROP-KKP-04',
    propertyType: 'Flat',
    locality: 'Madipakkam',
    address: 'Door 8B, Karthikeyapuram 2nd Main Rd, Madipakkam',
    sizeSqFt: 985,
    groundArea: 'UDS 420 Sqft',
    facing: 'East',
    roadWidthFt: 20,
    price: '72 Lakhs',
    priceNumeric: 7200000,
    ownerName: 'Owner Kumar',
    ownerContact: '+91 98844 12038',
    availableFrom: '2026-08-09',
    status: 'Not Available',
    isPotential: true,
    isApproved: true,
    isLocked: true,
    lockedAt: '2026-08-09',
    lockedBy: 'Admin (System)',
    crmStage: 'Under Negotiation',
    features: ['Lift Available', 'Covered Car Parking', 'Modular Kitchen'],
    onlineAdsPostedCount: 0,
    totalSiteVisits: 9,
  },
  {
    id: 'prop-5',
    title: 'Regal Residency 2 BHK Flat',
    propertyCode: 'PROP-RGL-05',
    propertyType: 'Flat',
    locality: 'Nanganallur',
    address: 'Regal Apartments, 4th Main Road, Nanganallur',
    sizeSqFt: 1050,
    groundArea: 'UDS 460 Sqft',
    facing: 'South',
    roadWidthFt: 20,
    price: '65 Lakhs',
    priceNumeric: 6500000,
    ownerName: 'Sriram Properties',
    ownerContact: '+91 95000 47556',
    availableFrom: '2025-06-01',
    status: 'Not Available',
    isPotential: false,
    isApproved: true,
    isLocked: true,
    crmStage: 'Listing',
    features: ['Near Anjaneyar Temple', 'Vaastu Compliant', '24h Water'],
    onlineAdsPostedCount: 0,
    totalSiteVisits: 12,
  },
  {
    id: 'prop-6',
    title: 'Padappai JV Land 4.5 Grounds',
    propertyCode: 'PROP-PDP-06',
    propertyType: 'Joint Venture',
    locality: 'Padappai',
    address: 'State Highway frontage, Padappai',
    sizeSqFt: 10800,
    groundArea: '4.5 Grounds',
    facing: 'North-East',
    roadWidthFt: 40,
    price: '3.5 Cr (Advance)',
    priceNumeric: 35000000,
    ownerName: 'Anil JV Landowner',
    ownerContact: '+91 98847 56066',
    availableFrom: '2026-08-17',
    status: 'Available',
    isPotential: true,
    waitingForApproval: false,
    waitingForModification: true,
    modificationReason: 'Clarify JV sharing ratio (50:50 vs 55:45) and check if latest legal Encumbrance Certificate (EC) is obtained from registrar.',
    modificationRequestedBy: 'MD (Admin)',
    modificationRequestedAt: '2026-09-17',
    isApproved: false,
    isLocked: false,
    crmStage: 'Verification',
    features: ['Commercial / Residential mixed', 'Outright or JV Allowed', 'Clear Title'],
    onlineAdsPostedCount: 5,
    totalSiteVisits: 3,
  },
  {
    id: 'prop-7',
    title: 'Lakshmi Nagar G+3 Builder Floor Building',
    propertyCode: 'PROP-LAK-07',
    propertyType: 'Flat',
    locality: 'Nanganallur',
    address: 'Lakshmi Nagar 3rd St, Nanganallur',
    sizeSqFt: 6000,
    groundArea: '1.5 Ground',
    facing: 'East',
    roadWidthFt: 30,
    price: '1.20 Cr each (6 Flats)',
    priceNumeric: 72000000,
    ownerName: 'Kumar Builder',
    ownerContact: '+91 98844 12038',
    availableFrom: '2026-04-19',
    status: 'Available',
    isPotential: true,
    isApproved: false,
    isLocked: false,
    crmStage: 'Verification',
    features: ['G+3 structure with 6 flats', '1000 sq ft each', 'Carpet 835 sqft', '12,000/sqft'],
    onlineAdsPostedCount: 12,
    totalSiteVisits: 4,
  }
];

export const initialBuyerLeads: BuyerLead[] = [
  {
    id: 'buyer-1',
    date: '2026-08-20',
    name: 'Annamalai (20-8-26) 20th',
    contactNo: '88254 43965',
    enquiryMode: 'Property Plus',
    enquiryFor: 'Purchase',
    propertyType: 'Plot',
    propertyArea: '2400 sq ft (1 Ground)',
    propertyAddress: 'Plot No 14, 20th Street, Nanganallur, Chennai',
    areaOfLand: '1 Ground (40 x 60)',
    areaOfBuilding: 'Nil (Vacant Plot)',
    ownershipType: 'Freehold Patta',
    foodPreference: 'Veg',
    religion: 'Hindu',
    budget: '2.5 Cr',
    preferredLocality: '20th Street, Nanganallur',
    requirement: 'He enquired about 20th Street plot. Details shared.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Site visit confirmed for this week. Looking for outright purchase.',
    comments: 'Very interested in clear patta documentation. Fast decision maker.',
    isPotential: true,
    potentialApproved: true,
    waitingForApproval: false,
    isLocked: true,
    lockedFields: ['name', 'contactNo', 'date', 'propertyType', 'propertyArea', 'propertyAddress'],
    lockedAt: '2026-08-21',
    lockedBy: 'Admin (System)',
    crmStage: 'Approved / Locked',
    tags: ['Property Plus', 'High Budget', 'Plot Buyer'],
  },
  {
    id: 'buyer-2',
    date: '2026-08-21',
    name: 'Aishwarya (21-8-26)',
    contactNo: '95662 49280',
    enquiryMode: 'Property Plus',
    enquiryFor: 'Purchase',
    propertyType: 'Flat',
    propertyArea: '1050 sq ft',
    propertyAddress: '15, 3rd Main Road, Nanganallur',
    budget: '80 Lakhs',
    preferredLocality: 'Nanganallur / Guduvanchery',
    requirement: 'She enquired about plots in and around Nanganallur. Her budget is 80 L only. Referred Guduvanchery and Urapakkam also.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Not interested in outskirts; looking strictly inside city limits.',
    comments: 'Needs follow up if new budget flats appear.',
    isPotential: false,
    potentialApproved: false,
    waitingForApproval: false,
    isLocked: false,
    crmStage: 'New Lead',
    tags: ['Property Plus', 'Budget Constrained'],
  },
  {
    id: 'buyer-3',
    date: '2026-08-21',
    name: 'Jaishankar (21-8-26)',
    contactNo: '+1 (713) 909-5396',
    enquiryMode: 'Property Plus',
    enquiryFor: 'Purchase',
    propertyType: 'Independent House',
    propertyArea: '3200 sq ft',
    propertyAddress: 'No. 8, Hindu Colony 4th Cross, Nanganallur',
    areaOfLand: '1.5 Grounds',
    areaOfBuilding: '2400 sq ft G+1',
    ownershipType: 'Ancestral Freehold',
    foodPreference: 'Veg',
    religion: 'Hindu',
    budget: '2.5 Cr',
    preferredLocality: '20th Street',
    requirement: 'He enquired about 20th Street. Details shared. He will visit and come to office for further details.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'NRI client based in Houston. Brother will accompany for physical inspection.',
    comments: 'Will finalize on office visit.',
    isPotential: true,
    potentialApproved: false,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-17',
    isLocked: false,
    crmStage: 'Potential',
    tags: ['Property Plus', 'NRI', 'High Budget'],
  },
  {
    id: 'buyer-4',
    date: '2026-08-22',
    name: 'FB Sundar (22-8-26)',
    contactNo: '+49 178 1032942',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: 'Plot',
    propertyArea: '1800 sq ft',
    propertyAddress: '24, Modern Suburb, Nanganallur',
    areaOfLand: '1800 sq ft',
    areaOfBuilding: 'Nil',
    ownershipType: 'CMDA Approved Patta',
    foodPreference: 'Any',
    religion: 'Hindu',
    budget: '2 Cr',
    preferredLocality: '20th Street',
    requirement: 'He enquired about 20th Street. Details shared via WhatsApp.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Responded positively on WhatsApp catalog.',
    comments: 'Lead from Europe FB Ad campaign.',
    isPotential: true,
    potentialApproved: false,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-18',
    isLocked: false,
    crmStage: 'Potential',
    tags: ['Facebook', 'NRI'],
  },
  {
    id: 'buyer-5',
    date: '2026-08-22',
    name: 'Dilipkumar (22-8-26)',
    contactNo: '98401 27001',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: 'Plot',
    budget: '1.8 Cr',
    preferredLocality: '20th Street',
    requirement: 'He enquired about 20th Street. Details shared.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Wants half ground or compact parcel.',
    comments: 'Shared broker commission structure.',
    isPotential: true,
    potentialApproved: false,
    waitingForApproval: false,
    waitingForModification: true,
    modificationReason: 'Plot survey number missing and owner contact not confirmed. Please verify and re-submit.',
    modificationRequestedBy: 'GS (Admin)',
    modificationRequestedAt: '2026-09-18',
    isLocked: false,
    crmStage: 'Potential',
    tags: ['Facebook', 'Direct Buyer'],
  },
  {
    id: 'buyer-6',
    date: '2026-08-22',
    name: 'Padma (22-8-26)',
    contactNo: '94448 96359',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: 'Plot / House',
    budget: '1.50 Cr',
    preferredLocality: 'Indira Nagar / Nanganallur',
    requirement: 'She is in Indira Nagar. Budget 1.50cr.',
    firstCallHandledBy: 'Muthukumar',
    recentUpdate: 'Scheduled 1-on-1 meeting at her residence.',
    comments: 'Looking for prompt booking.',
    isPotential: true,
    potentialApproved: false,
    isLocked: false,
    crmStage: 'Negotiation',
    tags: ['Facebook', 'Ready Buyer'],
  },
  {
    id: 'buyer-7',
    date: '2026-08-22',
    name: 'Rajkumar (22-8-26)',
    contactNo: '99401 81098',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: 'Flat',
    budget: '60 Lakhs',
    preferredLocality: 'Nanganallur',
    requirement: 'Budget didn’t suitable to him for 20th St.',
    firstCallHandledBy: 'Muthukumar',
    recentUpdate: 'Referred to Guduvanchery projects.',
    comments: 'Low budget for prime locality.',
    isPotential: false,
    potentialApproved: false,
    isLocked: false,
    crmStage: 'New Lead',
    tags: ['Facebook'],
  },
  {
    id: 'buyer-8',
    date: '2026-08-23',
    name: 'Gopalakrishnan (23-8-26)',
    contactNo: '98848 27469',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: 'Plot',
    budget: '2.4 Cr',
    preferredLocality: '20th Street',
    requirement: 'He enquired about 20th Street. Details shared.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Negotiating price reduction with MD.',
    comments: 'Wants to finalize before end of month.',
    isPotential: true,
    potentialApproved: true,
    isLocked: true,
    lockedAt: '2026-08-24',
    lockedBy: 'Admin (System)',
    crmStage: 'Negotiation',
    tags: ['Facebook', 'Hot Lead'],
  },
  {
    id: 'buyer-9',
    date: '2026-08-18',
    name: 'Ranganathan Builder (18-8-26)',
    contactNo: '96295 93818',
    enquiryMode: 'Property Plus',
    enquiryFor: 'Purchase',
    propertyType: 'Plot',
    budget: '50 Lakhs',
    preferredLocality: 'Guduvanchery',
    requirement: 'He is a builder enquired about Guduvanchery. Details shared.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Wants 2 plots for immediate construction.',
    comments: 'Good builder contact for recurring sales.',
    isPotential: true,
    potentialApproved: true,
    isLocked: false,
    crmStage: 'Site Visit Scheduled',
    tags: ['Property Plus', 'Builder'],
  },
  {
    id: 'buyer-10',
    date: '2026-08-17',
    name: 'Balaji (Ex-Imperial staff)',
    contactNo: '96000 47022',
    enquiryMode: 'Property Plus',
    enquiryFor: 'Purchase',
    propertyType: '2 BHK / Flat',
    budget: '75 Lakhs',
    preferredLocality: 'Nanganallur / TG Nagar',
    requirement: 'He required flat for daughter in Nanganallur and TG Nagar.',
    firstCallHandledBy: 'Muthukumar',
    recentUpdate: 'Karthikeyapuram and Regal details sent.',
    comments: 'Prefers Ground or First floor.',
    isPotential: true,
    potentialApproved: false,
    isLocked: false,
    crmStage: 'Potential',
    tags: ['Property Plus', 'Urgent Flat'],
  },
  {
    id: 'buyer-11',
    date: '2026-08-23',
    name: 'Santhosh Kumar (23-8-26)',
    contactNo: '96888 40540',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: '2 BHK',
    budget: '1.20 Cr',
    preferredLocality: 'Nanganallur',
    requirement: 'He enquired about our projects. He needs 2 BHK. Budget 1.20 Cr.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Sent details of Lakshmi Nagar new project.',
    comments: 'Finance pre-approved with HDFC Bank.',
    isPotential: true,
    potentialApproved: true,
    isLocked: false,
    crmStage: 'Potential',
    tags: ['Facebook', 'Pre-approved Loan'],
  },
  {
    id: 'buyer-12',
    date: '2026-08-22',
    name: 'Subramani (22-8-26)',
    contactNo: '97918 16802',
    enquiryMode: 'Facebook',
    enquiryFor: 'Purchase',
    propertyType: '2 BHK',
    budget: '90 Lakhs',
    preferredLocality: 'Nanganallur',
    requirement: 'He enquired about our projects. Needs 2 BHK flat.',
    firstCallHandledBy: 'Venkatesh',
    recentUpdate: 'Awaiting site visit timing.',
    comments: 'Family will join for inspection.',
    isPotential: false,
    potentialApproved: false,
    isLocked: false,
    crmStage: 'New Lead',
    tags: ['Facebook'],
  }
];

export const initialCustomerLeads: CustomerLead[] = [
  {
    id: 'cust-e',
    date: '2026-09-18',
    name: 'Customer E (this is Customer Name)',
    contactNo: '+91 98401 23456',
    propertyType: 'Plot',
    propertyArea: '2400 sq ft (1 Ground)',
    propertyAddress: 'No. 18, 4th Main Road, Nanganallur, Chennai',
    areaOfLand: '2400 sq ft',
    areaOfBuilding: 'Nil',
    ownershipType: 'Clear Patta Freehold',
    foodPreference: 'Veg',
    religion: 'Hindu',
    customerType: 'Seller',
    propertyOffered: '1 Ground clear plot in prime Nanganallur location',
    locality: 'Nanganallur',
    expectedPrice: '2.40 Cr',
    notes: 'Direct owner selling inherited prime residential plot. Title verified by legal advisor. Ready for outright sale.',
    handledBy: 'Venkatesh',
    isPotential: true,
    isApproved: true,
    waitingForApproval: false,
    isLocked: true,
    lockedFields: ['name', 'contactNo', 'date', 'propertyType', 'propertyArea', 'propertyAddress'],
    lockedAt: '2026-09-18',
    lockedBy: 'Admin',
    crmStage: 'Admin Approved',
    statusTag: 'Approved & Locked',
  },
  {
    id: 'cust-b',
    date: '2026-09-17',
    name: 'Customer B',
    contactNo: '+91 97890 54321',
    propertyType: 'Independent House',
    propertyArea: '3200 sq ft built-up on 1.5 Grounds',
    propertyAddress: 'Door 15, Lakshmi Nagar 3rd Street, Nanganallur',
    areaOfLand: '3600 sq ft',
    areaOfBuilding: 'G+1 Independent Villa',
    ownershipType: 'Individual Patta',
    foodPreference: 'Any',
    religion: 'All Welcome',
    customerType: 'Seller',
    propertyOffered: 'G+1 Independent House in Lakshmi Nagar',
    locality: 'Lakshmi Nagar, Nanganallur',
    expectedPrice: '3.10 Cr',
    notes: 'Seller moving abroad. Looking for fast closure within 45 days. Documents collected.',
    handledBy: 'Muthukumar',
    isPotential: true,
    isApproved: true,
    waitingForApproval: false,
    isLocked: false,
    crmStage: 'Potential Review',
    statusTag: 'Potential Seller',
  },
  {
    id: 'cust-y',
    date: '2026-09-15',
    name: 'Customer Y',
    contactNo: '+91 98410 88776',
    propertyType: 'Joint Venture',
    propertyArea: '3 Grounds (7200 sq ft)',
    propertyAddress: 'Near Palavanthangal Railway Station, Chennai',
    areaOfLand: '7200 sq ft',
    areaOfBuilding: 'Old building to be demolished',
    ownershipType: 'Family Partition Deed',
    foodPreference: 'Veg',
    religion: 'Hindu',
    customerType: 'Landowner',
    propertyOffered: '3 Grounds prime JV land near station',
    locality: 'Palavanthangal',
    expectedPrice: '55:45 Ratio + 1 Cr Advance',
    notes: 'Landowner meeting with MD completed. Architectural feasibility study underway.',
    handledBy: 'Venkatesh',
    isPotential: true,
    isApproved: false,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-16',
    isLocked: false,
    crmStage: 'Potential Review',
    statusTag: 'Waiting Approval',
  },
  {
    id: 'cust-d',
    date: '2026-09-12',
    name: 'Customer D',
    contactNo: '+91 94441 99880',
    propertyType: 'Commercial',
    propertyArea: '1800 sq ft Shop Space',
    propertyAddress: 'Medavakkam Main Road, Madipakkam',
    areaOfLand: '1800 sq ft',
    areaOfBuilding: 'Ground floor commercial showroom',
    ownershipType: 'Commercial Freehold',
    foodPreference: 'Any',
    religion: 'All Welcome',
    customerType: 'Builder',
    propertyOffered: 'Road-facing commercial shop space',
    locality: 'Madipakkam',
    expectedPrice: '1.75 Cr',
    notes: 'Builder offering roadside commercial space with rental yield of 65k/month.',
    handledBy: 'Venkatesh',
    isPotential: true,
    isApproved: false,
    waitingForApproval: false,
    waitingForModification: true,
    modificationReason: 'Rental agreement copy and maintenance charges breakdown needed before promoting to prospective investor list.',
    modificationRequestedBy: 'GS (Admin)',
    modificationRequestedAt: '2026-09-18',
    isLocked: false,
    crmStage: 'Potential Review',
    statusTag: 'Waiting Modification',
  },
  {
    id: 'cust-1',
    date: '2026-08-17',
    name: 'Anil - Padappai JV',
    contactNo: '98847 56066',
    propertyType: 'Joint Venture',
    propertyArea: '4.5 Grounds (10,800 sq ft)',
    propertyAddress: 'State Highway Road, Near Bus Stop, Padappai',
    areaOfLand: '4.5 Grounds',
    areaOfBuilding: 'Nil (Vacant Land)',
    ownershipType: 'Freehold Patta',
    foodPreference: 'Any',
    religion: 'Hindu',
    customerType: 'Landowner',
    propertyOffered: '4.5 Grounds land in Padappai',
    locality: 'Padappai',
    expectedPrice: '3.5 Cr Advance / Outright',
    notes: 'He spoke to me and sent details of JV in Padappai. 4.5 grounds, 3.5 cr advance. Outright also fine.',
    handledBy: 'Venkatesh',
    isPotential: true,
    isApproved: true,
    waitingForApproval: false,
    isLocked: true,
    lockedFields: ['name', 'contactNo', 'date', 'propertyType', 'propertyArea', 'propertyAddress'],
    lockedAt: '2026-08-18',
    lockedBy: 'Admin',
    crmStage: 'Admin Approved',
    statusTag: 'Approved & Locked',
  },
  {
    id: 'cust-2',
    date: '2026-04-19',
    name: 'Owner Kumar (Lakshmi Nagar Flats)',
    contactNo: '+91 98844 12038',
    propertyType: 'Flat',
    propertyArea: '1000 sq ft each (6 Flats)',
    propertyAddress: 'No. 24, 2nd Main Road, Lakshmi Nagar, Nanganallur',
    areaOfLand: '1.5 Grounds Land Area',
    areaOfBuilding: 'G+3 Structure (6 Units)',
    ownershipType: 'Builder Freehold',
    foodPreference: 'Veg / Non-veg',
    religion: 'All Welcome',
    customerType: 'Builder',
    propertyOffered: 'G+3 building with 6 flats, 1000 sq ft each',
    locality: 'Lakshmi Nagar, Nanganallur',
    expectedPrice: '12,000 / sq ft',
    notes: 'Carpet area 835 sq ft, 1.5 ground land area, 30 feet road width. Entrusted exclusive selling rights.',
    handledBy: 'Venkatesh',
    isPotential: true,
    isApproved: true,
    waitingForApproval: false,
    isLocked: true,
    lockedFields: ['name', 'contactNo', 'date', 'propertyType', 'propertyArea', 'propertyAddress'],
    lockedAt: '2026-04-20',
    lockedBy: 'Admin',
    crmStage: 'Mandate Signed',
    statusTag: 'Approved & Locked',
  },
  {
    id: 'cust-3',
    date: '2026-04-19',
    name: 'Jagan (Durairaj St Flat)',
    contactNo: '+91 99403 41963',
    propertyType: 'Flat',
    propertyArea: '950 sq ft',
    propertyAddress: 'Door 12B, Durairaj Street, Pazhavanthangal, Chennai',
    areaOfLand: 'UDS 410 sq ft',
    areaOfBuilding: '950 sq ft 2 BHK',
    ownershipType: 'Individual Freehold',
    foodPreference: 'Veg',
    religion: 'Hindu',
    customerType: 'Seller',
    propertyOffered: '2 BHK Flat in Durairaj St, Pazhavanthangal',
    locality: 'Pazhavanthangal',
    expectedPrice: '62 Lakhs',
    notes: 'He is selling his flat. Spoke to him and collected documents. Site visit done with client.',
    handledBy: 'Venkatesh',
    isPotential: true,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-17',
    isApproved: false,
    isLocked: false,
    crmStage: 'Potential Review',
    statusTag: 'Waiting Approval',
  },
  {
    id: 'cust-4',
    date: '2026-04-07',
    name: 'Mediator Ragavan',
    contactNo: '+91 94443 81928',
    propertyType: 'Plot',
    propertyArea: '1200 sq ft (Half Ground)',
    propertyAddress: 'Survey No 88/2, Kannan Nagar 3rd St, Palavanthangal',
    areaOfLand: '1200 sq ft',
    areaOfBuilding: 'Nil',
    ownershipType: 'Clear Patta',
    foodPreference: 'Veg',
    religion: 'Hindu',
    customerType: 'Landowner',
    propertyOffered: 'Half ground plot in Palavanthangal',
    locality: 'Palavanthangal',
    expectedPrice: '1.25 Cr',
    notes: 'He has half ground in Palavanthangal. Asked to send documents for matching with our registered buyers.',
    handledBy: 'Venkatesh',
    isPotential: true,
    waitingForApproval: true,
    waitingForApprovalAt: '2026-09-18',
    isApproved: false,
    isLocked: false,
    crmStage: 'Potential Review',
    statusTag: 'Waiting Approval',
  },
  {
    id: 'cust-5',
    date: '2026-08-12',
    name: 'Mediator Baskar',
    contactNo: '98405 14423',
    propertyType: 'Commercial',
    propertyArea: '3600 sq ft (1.5 Grounds)',
    propertyAddress: 'GST Main Road Junction, Guduvanchery',
    customerType: 'Seller',
    propertyOffered: 'Guduvanchery commercial plots',
    locality: 'Guduvanchery',
    expectedPrice: 'Market Price',
    notes: 'He enquired about Guduvanchery. He will bring direct buyers. Informed about side by side service charges. He agreed.',
    handledBy: 'Venkatesh',
    isPotential: false,
    waitingForApproval: false,
    isApproved: false,
    isLocked: false,
    crmStage: 'Lead Intake',
    statusTag: 'New Lead',
  },
  {
    id: 'cust-6',
    date: '2026-08-22',
    name: 'Sundararaman (Thillai Ganga Nagar)',
    contactNo: '94440 23119',
    propertyType: 'Independent House',
    propertyArea: '2800 sq ft on 1.25 Grounds',
    propertyAddress: 'Plot 45, 14th Street, Thillai Ganga Nagar, Nanganallur',
    customerType: 'Seller',
    propertyOffered: 'Independent Bungalow',
    locality: 'Nanganallur',
    expectedPrice: '2.80 Cr',
    notes: 'Direct owner selling ancestral bungalow. Clear documents, single owner.',
    handledBy: 'Muthukumar',
    isPotential: false,
    waitingForApproval: false,
    isApproved: false,
    isLocked: false,
    crmStage: 'Lead Intake',
    statusTag: 'New Lead',
  }
];

export const initialActivitiesLogs: ActivityLog[] = [
  {
    id: 'log-1',
    date: '2026-08-20',
    time: '10:30 AM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityId: 'buyer-1',
    entityName: 'Annamalai (20-8-26) 20th',
    contactNumber: '88254 43965',
    propertyType: 'Plot',
    budget: '2.5 Cr',
    requirement: 'He enquired about 20th Street plot. Details shared.',
    callNumber: 1,
    notes: 'Details of 20th street North-East plot explained. Sent brochure over WhatsApp.',
    recentUpdate: 'He enquired about 20th Street plot. Details shared.',
    comments: 'Fast moving lead',
    handledBy: 'Venkatesh',
    status: 'Completed',
    nextFollowUpDate: '2026-08-24',
  },
  {
    id: 'log-2',
    date: '2026-08-21',
    time: '11:15 AM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityId: 'buyer-2',
    entityName: 'Aishwarya (21-8-26)',
    contactNumber: '95662 49280',
    propertyType: 'Plot',
    budget: '80 L',
    requirement: 'Plots in Nanganallur within 80 Lakhs',
    callNumber: 1,
    notes: 'Explained market rates in Nanganallur (120L+). Suggested Guduvanchery.',
    recentUpdate: 'Not interested in outskirts.',
    comments: 'Budget too low for requested area.',
    handledBy: 'Venkatesh',
    status: 'Completed',
  },
  {
    id: 'log-3',
    date: '2026-08-21',
    time: '04:00 PM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityId: 'buyer-3',
    entityName: 'Jaishankar (21-8-26)',
    contactNumber: '+1 (713) 909-5396',
    propertyType: 'Plot',
    budget: '2.5 Cr',
    requirement: 'NRI purchase 20th Street',
    callNumber: 1,
    notes: 'Long international call. Discussed power of attorney & bank clearance.',
    recentUpdate: 'He enquired about 20th Street. Details shared. Will visit office.',
    comments: 'High priority NRI lead',
    handledBy: 'Venkatesh',
    status: 'Completed',
    nextFollowUpDate: '2026-08-28',
  },
  {
    id: 'log-4',
    date: '2026-08-22',
    time: '02:30 PM',
    activityTypeId: 'act-3',
    activityTypeName: '121 meeting in office',
    entityType: 'buyer',
    entityId: 'buyer-1',
    entityName: 'Annamalai',
    contactNumber: '88254 43965',
    propertyType: 'Plot',
    budget: '2.5 Cr',
    requirement: '20th St Plot review with MD',
    notes: 'Came to office with legal advisor. Reviewed FMB sketch, parent documents.',
    recentUpdate: 'Legal verification positive.',
    comments: 'Ready to advance.',
    handledBy: 'Venkatesh',
    status: 'Completed',
  },
  {
    id: 'log-5',
    date: '2026-08-23',
    time: '09:00 AM',
    activityTypeId: 'act-5',
    activityTypeName: 'Property visit',
    entityType: 'property',
    entityId: 'prop-1',
    entityName: '20th Street Plot Visit with Gopalakrishnan',
    contactNumber: '98848 27469',
    propertyType: 'Plot',
    budget: '2.4 Cr',
    requirement: 'Site inspection and boundary measurement',
    notes: 'Walkthrough conducted with Gopalakrishnan and family. Checked borewell point.',
    recentUpdate: 'Requested MD meeting on Sunday.',
    comments: 'Positive feedback.',
    handledBy: 'Venkatesh',
    status: 'Completed',
  },
  {
    id: 'log-6',
    date: '2026-08-29',
    time: '10:00 AM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Kumar (14/3)',
    contactNumber: '+91 96182 43576',
    propertyType: 'Plot',
    budget: 'NA',
    requirement: 'Needs half a ground in Nanganallur, Adambakkam, Madipakkam',
    callNumber: 1,
    notes: '29-08-2026 Guduvanchery and Urapakkam details sent',
    recentUpdate: '29-08-2026 Guduvanchery and Urapakkam details sent',
    comments: 'DAR Call 1',
    handledBy: 'Venkatesh',
    status: 'Completed',
    nextFollowUpDate: '2026-09-03',
  },
  {
    id: 'log-7',
    date: '2026-09-03',
    time: '11:30 AM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Kumar (14/3)',
    contactNumber: '+91 96182 43576',
    propertyType: 'Plot',
    budget: 'NA',
    requirement: 'Follow up on Guduvanchery options',
    callNumber: 2,
    notes: '03-09-2026 No answer. Will retry later.',
    recentUpdate: '03-09-2026 (No answer)',
    comments: 'DAR Call 2',
    handledBy: 'Venkatesh',
    status: 'Follow-up Required',
  },
  {
    id: 'log-8',
    date: '2026-08-29',
    time: '03:15 PM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Venkatesan (16/3)',
    contactNumber: '+91 72999 99850',
    propertyType: 'Plot / Resale Flat',
    budget: '65 L',
    requirement: 'Vegetarian. Resale flat required in NNR. Ground Floor or middle Floor',
    callNumber: 1,
    notes: '29-08-2026 Guduvanchery and Urapakkam details sent',
    recentUpdate: 'Details sent over WhatsApp',
    comments: 'DAR Call 1',
    handledBy: 'Venkatesh',
    status: 'Completed',
    nextFollowUpDate: '2026-09-03',
  },
  {
    id: 'log-9',
    date: '2026-09-03',
    time: '12:00 PM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Venkatesan (16/3)',
    contactNumber: '+91 72999 99850',
    propertyType: 'Resale Flat',
    budget: '65 L',
    requirement: 'Call 2 follow-up',
    callNumber: 2,
    notes: '03-09-2026 (Already purchased a flat in Nanganallur)',
    recentUpdate: 'Closed out - flat purchased elsewhere.',
    comments: 'Closed lead',
    handledBy: 'Venkatesh',
    status: 'Completed',
  },
  {
    id: 'log-10',
    date: '2026-08-29',
    time: '04:00 PM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Govind Raj Independent House Enquiry',
    contactNumber: '+91 81249 75945',
    propertyType: 'Independent House',
    budget: '1.30 Cr',
    requirement: 'Old enquirer. 20th Street land Enquiry. Budget didn’t suitable.',
    callNumber: 1,
    notes: '29-08-2026 Guduvanchery and Urapakkam details sent',
    recentUpdate: 'Sent alternate locations',
    comments: 'DAR Call 1',
    handledBy: 'Venkatesh',
    status: 'Completed',
    nextFollowUpDate: '2026-09-03',
  },
  {
    id: 'log-11',
    date: '2026-09-03',
    time: '02:00 PM',
    activityTypeId: 'act-1',
    activityTypeName: 'Mobile call',
    entityType: 'buyer',
    entityName: 'Govind Raj Independent House Enquiry',
    contactNumber: '+91 81249 75945',
    propertyType: '3 BHK Flat',
    budget: '1.30 Cr',
    requirement: '03-09-2026 (he need only for 3 bhk flat for palavanthangal area, ullagaram & puzhuthivakkam area only, budget 1.30 crores)',
    callNumber: 2,
    notes: 'Updated requirement to 3BHK flat in Palavanthangal/Ullagaram',
    recentUpdate: 'Refined search zone',
    comments: 'High chance if suitable flat matched',
    handledBy: 'Venkatesh',
    status: 'Completed',
  },
  {
    id: 'log-12',
    date: '2026-08-22',
    time: '05:00 PM',
    activityTypeId: 'act-6',
    activityTypeName: 'Buyer and Customer Mobile Conference',
    entityType: 'general',
    entityName: 'Conf: Padma (Buyer) & Kumar (Owner)',
    contactNumber: '94448 96359',
    propertyType: 'Flat',
    budget: '1.50 Cr',
    requirement: 'Price clarification on Lakshmi Nagar flat',
    notes: 'Three way conference held. Discussed registration timeline and UDS percentage.',
    recentUpdate: 'Conference successful.',
    comments: 'Next step is direct 121 meeting',
    handledBy: 'Muthukumar',
    status: 'Completed',
  }
];

// Enquiry statistics directly reflecting PDF Page 2
export const enquiryStatisticsData = [
  { source: 'Nanganallur Voice', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 0, '23-08-2026': 0 }, total: 0 },
  { source: 'Nanganallur Speaks', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 0, '23-08-2026': 0 }, total: 0 },
  { source: 'Facebook', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 5, '23-08-2026': 3 }, total: 8 },
  { source: 'Times of India', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 0, '23-08-2026': 0 }, total: 0 },
  { source: 'Hindu / Property Plus', counts: { '17-08-2026': 2, '18-08-2026': 2, '19-08-2026': 0, '20-08-2026': 1, '21-08-2026': 2, '22-08-2026': 0, '23-08-2026': 0 }, total: 7 },
  { source: 'Board', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 0, '23-08-2026': 0 }, total: 0 },
  { source: 'Others', counts: { '17-08-2026': 0, '18-08-2026': 0, '19-08-2026': 0, '20-08-2026': 0, '21-08-2026': 0, '22-08-2026': 0, '23-08-2026': 0 }, total: 0 },
];

// Weekly advertisement report directly reflecting PDF Page 3
export const weeklyAdsReportData = [
  {
    property: 'Regal',
    onlineAds: 'NIL',
    offlineAds: 'NIL',
    totalSiteVisits: 'NIL',
    status: 'Not Available',
    availableFrom: '01-06-2025',
  },
  {
    property: '20th Street',
    onlineAds: 'Posted in 31 groups in FB',
    offlineAds: 'NIL',
    totalSiteVisits: '14 visits',
    status: 'Available',
    availableFrom: '30-11-2025',
  },
  {
    property: 'Karthikeyapuram Flat',
    onlineAds: 'NIL',
    offlineAds: 'NIL',
    totalSiteVisits: '9 visits',
    status: 'Not Available',
    availableFrom: '09-08-2026',
  },
  {
    property: 'Urapakkam',
    onlineAds: 'Posted in 31 groups in FB',
    offlineAds: 'NIL',
    totalSiteVisits: '6 visits',
    status: 'Available',
    availableFrom: '01-11-2025',
  },
  {
    property: 'Guduvanchery',
    onlineAds: 'Posted in 31 groups in FB',
    offlineAds: 'NIL',
    totalSiteVisits: '8 visits',
    status: 'Available',
    availableFrom: '04-06-2026',
  },
];

export const sampleWeeklyAds: import('./types').WeeklyAdItem[] = [
  {
    id: 'ad-1',
    propertyTitle: '20th Street Plot',
    newspaperOrPortal: 'Facebook (31 Groups)',
    weekStartDate: '2026-08-17',
    cost: '₹1,500',
    enquiriesGenerated: 8,
    siteVisitsBooked: 14,
  },
  {
    id: 'ad-2',
    propertyTitle: '20th Street Residential Plot',
    newspaperOrPortal: 'Property Plus (The Hindu)',
    weekStartDate: '2026-08-17',
    cost: '₹4,800',
    enquiriesGenerated: 7,
    siteVisitsBooked: 6,
  },
  {
    id: 'ad-3',
    propertyTitle: 'Guduvanchery Township Plots',
    newspaperOrPortal: 'Facebook (31 Groups)',
    weekStartDate: '2026-08-17',
    cost: '₹1,500',
    enquiriesGenerated: 5,
    siteVisitsBooked: 8,
  },
  {
    id: 'ad-4',
    propertyTitle: 'Urapakkam Land',
    newspaperOrPortal: 'Facebook (31 Groups)',
    weekStartDate: '2026-08-17',
    cost: '₹1,500',
    enquiriesGenerated: 4,
    siteVisitsBooked: 6,
  },
  {
    id: 'ad-5',
    propertyTitle: 'Karthikeyapuram Flat',
    newspaperOrPortal: 'Nanganallur Voice',
    weekStartDate: '2026-08-10',
    cost: '₹2,200',
    enquiriesGenerated: 3,
    siteVisitsBooked: 9,
  },
];
